#!/bin/bash

screen -r -S megah -X quit
echo
echo "Lea el código QR a continuación y luego escriba el comando onbot para encende"
echo
echo "CTRL+C Para salir"
echo
sleep 2
node /etc/megahbot/index.js
